website:
  component: '@serverless/website'
  inputs:
    code:
      src: dist/serverless-angular
      hook: ng build --prod
    region: eu-west-1 #Ireland
    bucketName: georgikowebsite
    domain: www.georgiko.com
